name: Build and Deploy App

on:
  push:
    branches: [ "main" ]
    paths:
     - 'streamlit_app/**'
     - 'Dockerfile'
     - 'environment.yml'
     
permissions:
  id-token: write
  contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_REGISTRY_URL }}/bot:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_REGISTRY_URL }}/bot:${{ github.sha }}

      - name: Deploy web app container
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'as-arabot-lab-eastus'
          images: ${{ secrets.DOCKER_REGISTRY_URL }}/bot:${{ github.sha }}

      - name: Azure logout via Azure CLI
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az logout
            az cache purge
            az account clear  
