name: Build Linux Container Image and Push to ACR

on:
  push:
    branches: [ "main" ]
    paths:
     - 'streamlit_app/**'
     - 'Dockerfile'
     - 'environment.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_REGISTRY_URL }}/bot:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_REGISTRY_URL }}/bot:${{ github.sha }}
